logging.level:
  com.mgg.devicemanagement: DEBUG

spring:
  application:
    name: device-management
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:15432/devicemng
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, logging
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
info:
  app:
    name: Device Management Service
    description: This is an service to manage devices
    version: v1.0.0

springdoc:
  swagger-ui:
    disable-swagger-default-url: true